title: "Fauxxx’s Portfolio"
email: your-email@example.com
description: >-
  Controls Engineer | Robotics | UAVs | AI & Controls
baseurl: "" # leave empty for user.github.io
url: "https://ven0m-hue.github.io"

theme: minima
markdown: kramdown
paginate: 5
paginate_path: "/blog/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate

# Navigation links
header_pages:
  - about.md
  - projects.md
  - contact.md
  - resume.md
