title: "Fauxxx’s Portfolio"
description: "Controls Engineer | Robotics | UAVs | AI & Controls"
url: "https://ven0m-hue.github.io"
baseurl: "/vnayak.github.io"

author: Fauxxx
email: your-email@example.com

theme: jekyll-dash
