title: Fauxxx's Portfolio
description:
url: "https://ven0m-hue.github.io"
baseurl: "/vnayak.github.io"

author: Fauxxx

plugins:
  - jekyll-paginate
  - jekyll-feed

include:
  - assets/Fauxxx_Resume.pdf

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  posts:
    output: true
  projects:
    output: true

permalink: /blog/:title/

nav_links:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Resume
    url: /resume/
  - title: Contact
    url: /contact/

dash:
  theme_switcher: true
  date_format: "%b %-d, %Y"
  animation_speed: 50
  rtl: false
  disqus:
    shortname: your-disqus-shortname

  social_links:
    - url: https://x.com//some_random_dude
      icon: x
      color: cyan
    - url: https://github.com/ven0m-hue
      icon: github-square
      color: purple
    - url: https://linkedin.com/venkatesh_nayak/
      icon: linkedin
      color: blue
  show_author: false
