title: "Fauxxx’s Portfolio"
description: "Controls Engineer | Robotics | UAVs | AI & Controls"
url: "https://ven0m-hue.github.io"
baseurl: "/vnayak.github.io"

author: Fauxxx
email: your-email@example.com

# Navbar links
navbar-links:
  About Me: "/about/"
  Projects: "/projects/"
  Blog: "/blog/"
  Resume: "/resume/"
  Contact: "/contact/"


# Footer text
footer: "© 2025 Fauxxx"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
