title: Fauxxx's Portfolio
description:
url: https://vnayak.github.io
baseurl: "/vnayak.github.io"

author: Fauxxx

theme: jekyll-dash

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: "/blog/page:num/"

collections:
  posts:
    output: true
permalink: /blog/:title/

nav_links:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Blog
    url: /blog/
  - title: Resume
    url: /resume/
  - title: Contact
    url: /contact/

dash:
  theme_switcher: true
  date_format: "%b %-d, %Y"
  animation_speed: 50
  rtl: false
  disqus:
    shortname: your-disqus-shortname
  social_links:
    - url: https://twitter.com/bitbrain_
      icon: twitter-square
      color: cyan
    - url: https://bitbrain.itch.io
      icon: itch-io
      color: red
    - url: https://github.com/bitbrain
      icon: github-square
      color: purple
  show_author: false
