title: Fauxx Portfolio
description: "Controls Engineer | Robotics | UAV Systems"
theme: jekyll-theme-cayman

author: Fauxx


# Navigation links
navigation:
  - title: "Home"
    url: /
  - title: "About"
    url: /about
  - title: "Projects"
    url: /projects
  - title: "Contact"
    url: /contact
  - title: "Resume"
    url: /resume
